class ContinuedException(Exception):
    pass


class ProcessedException(Exception):
    pass
